### Retrieve problem input
< {%
    const day = 6;
    const year = 2022;

    request.variables.set("aocFormattedDay", day.toString().padStart(2, '0'))
    request.variables.set("aocDay", day.toString())
    request.variables.set("aocYear", year.toString())
%}

GET https://adventofcode.com/{{aocYear}}/day/{{aocDay}}/input
Accept: text/plain
Cookie: session={{session}}

>>! ../src/day{{aocFormattedDay}}/input.txt
